---
pagetitle: "A. John Woodill - Research"
output:
  html_document:
    theme: sandstone
    highlight: default
---

<br>
<br>



Peer-reviewed Papers
----------------------

*********

Villarino, E., Watson, J. R., Chust, G., **Woodill, A. J.**, Klempay, B., Jonsson, B., ... & Barton, A. D. (2022). Global beta diversity patterns

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; of microbial communities in the surface and deep ocean. Global Ecology and Biogeography.

Watson, J. R., & **Woodill, A. J.** (2022). Detecting illegal maritime activities from anomalous multiscale fleet behaviours. Fish and Fisheries.
[[**link**]](https://www.dropbox.com/s/6k5xkm411yz6kpp/Watson_Woodill_2022.pdf?dl=0)

**Woodill, A. J.**, Kavanaugh, M., Harte, M., & Watson, J. R. (2021). Ocean seascapes predict distant‐water fishing vessel incursions into 

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; exclusive economic zones. Fish and Fisheries. [[**link**]](https://www.dropbox.com/s/pw3g8mq0626gk1t/17052040.pdf?dl=1) 


**Woodill, A. J.**, Nakamoto, S. T., Kawabata, A. M., & Arita, S., Leung, P. (2021). Optimal spraying strategy to combat the coffee berry borer: 

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; A dynamic approach. Journal of Food and Agriculture Research. [[**link**]](https://www.dropbox.com/s/ie5xr8mzzzns0f6/1-s2.0-S2666154321000272-main.pdf?dl=1) 


**Woodill, A. J.**, Nakamoto, S. T., Kawabata, A. M., & Arita, S., Leung, P. (2019). The Impact of CBB on the Economics of Coffee Production in Hawai‘i: 

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  2007–2012 USDA Census Analysis. (May), 1-12 Insect Pests. [[**link**]](https://www.ctahr.hawaii.edu/oc/freepubs/pdf/IP-46.pdf)

**Woodill, A. J.**, Nakamoto, S. T., Kawabata, A. M., & Leung, P. (2017). To Spray or Not to Spray: A Decision Analysis of Coffee Berry Borer in Hawaii. 

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Insects, 8(4), 116. [[**link**]](http://www.mdpi.com/2075-4450/8/4/116)

**Woodill, A. J.**, Hemachandra, D., Nakamoto, S. T., & Leung, P. (2014). The Economics of Coffee Production in Hawai'i, (June),1-9. [[**link**]](http://www.ctahr.hawaii.edu/oc/freepubs/pdf/EI-25.pdf)

Richardson, G. M., Bowers, J., **Woodill, A. J.**, Barr, J. R., Gawron, J. M., & Levine, R. a. (2014). Topic Models: A Tutorial with R. International Journal  

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; of Semantic Computing, 08(01), 85-98. [[**link**]](http://www.worldscientific.com/doi/abs/10.1142/S1793351X14500044?journalCode=ijsc)

<br>
<br>

Patents
----------------------

*********

Watson, J. R., **Woodill, A. J.**, Kavanaugh, M. “An Operational Forecasting System Based On Anomalous Behaviors In Complex Systems.”

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; U.S. Patent Application No. 63/027,651 May 20, 2020. [[**link**]](https://patentimages.storage.googleapis.com/a7/b0/e5/664fcebaa52acb/US20220253727A1.pdf)

<br>
<br>

Working Papers
----------------------


*********


#### **The Impact of Conflict on Commercial Fishing Effort in Puerto Rico** (In review at Environmental Research Letters)

Nicolás X. Gómez-Andújar, A. John Woodill, Ciera Villegas, James R. Watson

Small-scale fisheries are vital to the food security of coastal communities worldwide, yet they face numerous challenges. In particular, fisheries conflicts arise when a marine resource is contested or disputed between a minimum of two human actors, at a discrete place and time. Despite relevance of fisheries conflicts for the marine economy, it is difficult to quantify the impact of conflict on fisheries production or on long-standing cooperative relationships that can e vital to the sustainability of a given fishery. Previous work addressing fisheries conflicts has focused on qualitative analysis and has had a limited focus on quantitative measurements of how fishers respond to conflict and cooperation. To address this knowledge gap, instances of conflict and cooperation amongst fishers in Puerto Rico were collected and categorized into different intensity levels. With these data, an econometric model was developed to estimate regional and monthly changes in fishing effort from 2012 to 2017, accounting for fisheries conflict while controlling for oceanographic factors. We found that the most intense fisheries conflict incidents (e.g., those that result in fines or lead to acts of violence) decreased commercial fisheries catch per trip by 4.9%. This result provides quantitative evidence for a positive feedback loop for the supply-induce scarcity hypothesis, highlighting the importance of managing fisheries conflicts to achieve long-term sustainability of fisheries. 

<br>
<br>

#### **Nutrients and Wine Yield: a Meta-Analysis** (In preperation for review at Journal of Wine Economics)

Alejandro Abarca, Patty Skinkis, A. John Woodill

Wine grapes are an important commodity grown in the US and throughout the world. While the majority of grapes are grown as table grapes, the fermentation of the grapes into wine is a unique preference to consumers. There exists a rich literature studying the phenology of grapevines -- including the role of nutrients and climate in the regular functioning of grapevines -- but the literature studying the effects of nutrients and weather on wine grape productivity is limited. This paper presents the first meta-analysis that focuses on investigating how nutrients affect the end-of-season yield. We first provide an extensive literature review on the impacts of wine grapes with nutrients and environmental variables that bridges the gap between economics and viticulture. We then extend recent modeling efforts to include the most relevant variables given by the literature and estimate a fixed effect regression analysis with environmental and field-level data. Our modeling results show that one of the most important nutrients, nitrogen, increases end-of-season yield by 26% with other variables aligning with the literature. The modeling results provide a general framework for understanding the marginal effects of nutrients and yield estimates. Finally, we close with a discussion on future research that can be gleaned from this meta-analysis. 

<br>
<br>

#### **Measuring the Economic Value of US Hawaii Longline Fishery** (In preparation for review at Frontiers in Marine Science)

A. John Woodill, Nicolás Gómez Andújar, Jonathan Sweeney, Maria Kavanaugh, Michael Harte, James R. Watson

The impacts of climate change are rapidly changing the world’s oceans. These disruptions have far-reaching implications for the health of the oceans, as well as the underlying ecosystem services that oceans provide us--namely food security. A major challenge in developing policies that can address these climate shocks is quantifying the value of the oceans. Oceans are vast and dynamic which makes measurement inherently challenging. An appropriate valuation must include not only their provision of ecosystem services but also how changes in the environment and human decisions will impact the ecosystem now and in the future. We use new economic methods to estimate the economic value of the US Longline Bigeye Tuna fishery as a “natural capital assets.” We link spatially explicit fishing effort data for the period 2010-2018 with ecological and economic data for the Hawaii longline fleet to estimate a dynamic welfare function. We recover a natural capital asset price for each year to show how shifts in capital stock and behaviors affect the price. Our results show that from 2010-2018, the natural capital asset price has increased from $*** to $***, with the capital price changing from $*** to $****.  Finally, we discuss challenges with estimate the natural capital asset price and future data needs to derive additional stocks and fisheries. These results highlight the need to objectively measure the economic value of fisheries to inform policies that will prepare us for changes in the provision of food and income gained from the oceans.

<br>
<br>

#### **Snow Pack Uncertainty and California’s Central Valley** (Finishing analysis)

A. John Woodill, Mark Raleigh, James R. Watson


Abstract
Agriculture in California’s Central Valley relies heavily on the winter snowfall in the Sierra Nevada Mountains that accumulates into snowpack. As the snowpack melts, the runoff flows into streams and rivers, thus increasing the water table and local water reservoirs used to supply water to residents and irrigate crops. The snowpack acts as a renewable resource that stores water that is then released throughout the year to irrigate crops in the Central Valley. However, in recent years, the level of snowpack during the winter months has been declining. The decline reduces the amount of available water to irrigate crops throughout the year, which forces prices to increase, thus impacting the profits of farmers. Further, the importance of the snowpack as a renewable asset suggests that climate change will depreciate the value of the asset from year-to-year. To address this problem, we develop a model that accounts for farm-land values and variation in environmental variables that include temperature, precipitation, and snowpack levels. We also incorporate changes in reservoir levels as snowpack changes to account for supply constraints in the model. We then apply the model into a natural capital asset framework to estimate the shadow price across different stocks of the snowpack. Our results provide an estimated shadow price across all years to show how the valuation changes based on changes in the snowpack levels. We then estimate how changes in the snowpack due to climate change will impact this valuation into the future. These results provide important insights into the value of snowpack as a capital asset and how the valuations will change into the future. 

<br>
<br>

####  **Adaptation and Nonlinear Temperature Effects: Second-Order Impacts of Climate Change that Cancel** (Finishing analysis)

A. John Woodill and Michael J. Roberts

A common theme in the economics of climate change is that farmers will adapt by planting different crops and adjusting other inputs, thereby offsetting negative impacts and further exploiting beneficial changes to climate. Many have suggested that adaptation is central to mitigating these negative impacts of climate change. However, measuring adaptation is difficult due to a variety of factors, such as responses to prices, institutional incentives, and technological progress. It is well-established that nonlinear (second-order) temperature effects are negative, but little is known about the effect size of adaptation. Basic microeconomic theory (the envelope theorem) suggests that adjustments in choices ought to be second-order relative to the direct effect of climate holding choices fixed. Using this framework, we use continuous crop-choice changes at the US county-level to estimate a first-order effect without adaptation and nonlinear effects with and without adaptation. We examine the distributions of crop choices over climate and consider the size of the positive second-order effects that may be gleaned from adaptation in relation to the negative second-order temperature effects from climate change. Our empirical results show that second-order effects with adaptation are similar to first order effects without adaptation, a direct result of the envelope theorem. We then show that aggregating over a continuum of climates produces countervailing positive and negative second-order effects that approximately cancel. Therefore, reasonably accurate climate change impacts can be discerned by aggregating local marginal effects of weather across the current distribution of activities and climates. These results suggest estimating local marginal effects, while holding choices fixed, can provide a more accurate assessment of climate change impacts without the need to estimate adaptation directly. 

<br>
<br>

#### **Adaptation to Climate Change: Disentangling Revenue and Crop Choice Responses** (Finishing analysis)

A. John Woodill and Michael J. Roberts

Adaptation by crop-switching has been suggested as a way to mitigate the harmfull effects of climate change on agriculture. Empirically, long run impact studies focus on cross-sectional associ- ations between agricultural outcomes and prevailing climate, implicitly accounting for adaptation; but the adaptive mechanism is not clear and the relationships may be confounded by unobserved factors. In this paper, we use a long history of crop choice and productivity outcomes to estimate effects of both weather and climate for major field crops in the United States. The approach lever- ages historical differences in climate trends across U.S. counties, differences that are large enough to span anticipated climate changes over the next 50 years, even after removing state-level trends. Climates are defined by backward-looking rolling means of the weather measures, with lag length selected via cross-validation. We then estimate the effect of climate change from a base level to uniform increases in temperature from 0-5°C. We find adaptation slightly reduces impacts relative to estimates that consider weather alone.


<br>
<br>


Active Grant Funding
----------------------


*********

2020-2024, Co-Principal Investigator — “High-Resolution Vineyard Nutrition Research Project”, a collaborative effort between WSU and Cornell, UC Davis, Oregon State, Rochester Institute of Technology, Virginia Tech, and USDA-ARS, funded through the National Institute of Food and Agriculture’s Specialty Crop Research Initiative Coordinated Agricultural Projects (CAP) grant ($4.75 million)

<br>

2022-2024, Co-Principal Investigator — “The Yield-Quality Paradigm: Using Long-Term, Multi-Vineyard Data to Understand Yield Management into the Future”, a collaborative effort at OSU with Patty Skinkis and Katie McLaughlin to disentangle field-level decision-making with a 10-year robust panel dataset that allows us to identify nutrient treatments and climate change impacts, USDA ARS Northwest Center for Small Fruits Research grant ($104,585)


<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-61017136-2', 'auto');
  ga('send', 'pageview');

</script>


